### ISSUE TITLE
Not compatible with the version of your running IDE

### ISSUE THREAD

**Issue by Thebluedragon7** [KartanHQ/intellij-expo#224]
### Describe the bug

Plugin is Incompatible with Webstorm 2024.3

`Incompatible: requires IDE build 241.* or earlier`

### Screenshots

![image](https://github.com/user-attachments/assets/a9f6fb86-7dbe-4a68-9306-37c2ba61f46e)

![image](https://github.com/user-attachments/assets/fba68fae-dca0-44a3-a915-756d754fdaf4)

**Comment by ZaLiTHkA** [comment]
I've had this twice now, first when WebStorm 2024.2 was released, and it took ages to "Solve some minor issues and update dependencies" and release `1.2.2`, which worked with 2024.2. then shortly after that WebStorm updated to 2024.3, and this plugin has yet to catch up to the bus.

to be completely honest, this plugin has spent more time "disabled" than "enabled" in my IDE, simply because it's been incompatible for the vast majority of the time.

---

just for the sake of understanding this better... is there any real benefit in locking down the version compatibility so tightly? could it perhaps work better to mark this plugin as compatible with `2024.*` (or whatever pattern would cover 2024.4, 2024.5, etc.)?

best case scenario, IDE updates would change things that don't relate to this plugin.. moderate case, it changes things so one or two plugin features don't work.. worst case, it causes the IDE to crash, in which case we would just disable it until there is an update. right now, our *only* option is to disable it and wait for dependencies to be updated and a new release with a new compatibility check, even if the plugin code requires no major changes.

please keep in mind: I have no experience building JetBrains plugins, I'm honestly just curious as to why it takes so long each time before this gets any updates..

**Comment by Thebluedragon7** [comment]
Incompatibility with IDE 2024.3 has been fixed by [release/1.2.4](https://github.com/KartanHQ/intellij-expo/releases/tag/v1.2.4).

Thanks @nekofar
